# This file is to reside in the base AmiraLocal directory
#
# In order to port your local packages to a new Amira version,
# adjust the path below and type gmake clean and gmake in 
# every package.

ifndef AMIRA_ROOT
    AMIRA_ROOT=C:/Program Files/ZIBAmira 2013.55
endif


