# This file is to reside in the base AmiraLocal directory
#
# In order to port your local packages to a new Amira version,
# adjust the path in GNUmakefile.setroot and type 
# gmake clean and gmake in every package.

ifndef AMIRA_LOCAL
    AMIRA_LOCAL=C:/Users/jug/ZIBAmiraLocal
endif

include $(AMIRA_LOCAL)/GNUmakefile.setroot
include $(AMIRA_ROOT)/GNUmakefile.rules

usersguide-online:

